### ISSUE TITLE
Open-Logic Cores Unusable Due to Incorrect Paths in Core Files

### ISSUE THREAD

**Issue by rbrglez** [fusesoc/fusesoc-cores#24]
Open-Logic cores assume that fusesoc searches for source files from the "local" .core file. instead fusesoc searches for source files from the top of the open-logic repository.

Current state of `olo_base.core`
```yaml
CAPI=2:

name : open-logic:open-logic:base:2.3.1
description : Basic Circuitry (e.g. FIFOs, CDCs, ...) see https://github.com/open-logic/open-logic/blob/main/doc/EntityList.md#base

filesets:
  rtl:
    files:
      - vhdl/olo_base_cc_n2xn.vhd
      - ...
      - vhdl/olo_base_cc_xn2n.vhd
    file_type : vhdlSource
    logical_name : olo

targets:
  default:
    filesets :
      - rtl
      
provider:
  name    : github
  user    : open-logic
  repo    : open-logic
  version : 2.3.1
```

Example of how `olo_base.core` should modify source file paths,
```yaml
CAPI=2:

name : open-logic:open-logic:base:2.3.1
description : Basic Circuitry (e.g. FIFOs, CDCs, ...) see https://github.com/open-logic/open-logic/blob/main/doc/EntityList.md#base

filesets:
  rtl:
    files:
      - src/base/vhdl/olo_base_cc_n2xn.vhd
      - ...
      - src/base/vhdl/olo_base_cc_xn2n.vhd
    file_type : vhdlSource
    logical_name : olo

targets:
  default:
    filesets :
      - rtl
      
provider:
  name    : github
  user    : open-logic
  repo    : open-logic
  version : 2.3.1
```
